export const routes = {
  adsManager: "AdsManager",
  auth: "Auth",
  aiAssistant: "AiAssistant",
  blogDetail: "BlogDetail",
  cafeDetail: "CafeDetail",
  chatDetail: "ChatDetail",
  conversations: "Conversations",
  create: "Create",
  createPostModal: "CreatePostModal",
  explore: "Explore",
  home: "Home",
  login: "Login",
  main: "Main",
  newChat: "NewChat",
  notifications: "Notifications",
  otherUserProfile: "OtherUserProfile",
  paymentOptions: "PaymentOptions",
  profile: "Profile",
  profileFollows: "ProfileFollows",
  region: "Region",
  register: "Register",
  reviewerDashboard: "ReviewerDashboard",
  settings: "Settings",
  userPosts: "UserPosts",
} as const;
